package com.appkitbox.winui4k.ribbon

/** The English (en) strings of [RibbonStrings] (exactly as defined by RibbonSpace). */
internal object RibbonStringsEn {
    val VALUES: Map<String, String> = linkedMapOf(
        "File" to "File",
        "CollapseRibbon" to "Collapse the Ribbon",
        "PinRibbon" to "Pin the Ribbon",
        "RibbonDisplayOptions" to "Ribbon display options",
        "FullScreenMode" to "Full-screen mode",
        "ShowTabsOnly" to "Show tabs only",
        "AlwaysShowRibbon" to "Always show Ribbon",
        "ShowPanelButtons" to "Show panel buttons",
        "ShowPanelTitles" to "Show panel titles",
        "MinimizeToTabs" to "Minimize to Tabs",
        "MinimizeToPanelTitles" to "Minimize to Panel Titles",
        "MinimizeToPanelButtons" to "Minimize to Panel Buttons",
        "CycleThroughAll" to "Cycle through All",
        "MinimizeRibbon" to "Minimize the Ribbon",
        "ShowFullRibbon" to "Show Full Ribbon",
        "ShowTabs" to "Show Tabs",
        "ShowPanels" to "Show Panels",
        "ShowGroupTitles" to "Show Panel Titles",
        "FloatPanel" to "Float Panel",
        "ReturnPanelToRibbon" to "Return Panel to Ribbon",
        "ReturnPanelsToRibbon" to "Return Panels to Ribbon",
        "PinPanel" to "Keep panel open",
        "UnpinPanel" to "Unpin panel",
        "ExpandPanel" to "More {0} commands",
        "RecentDocuments" to "Recent Documents",
        "SearchCommands" to "Search commands",
        "UseSimplifiedRibbon" to "Simplified Ribbon",
        "UseClassicRibbon" to "Classic Ribbon",
        "ShowQuickAccessToolbar" to "Show Quick Access Toolbar",
        "HideQuickAccessToolbar" to "Hide Quick Access Toolbar",
        "ShowAboveRibbon" to "Show Above the Ribbon",
        "ShowBelowRibbon" to "Show Below the Ribbon",
        "ShowCommandLabels" to "Show Command Labels",
        "CustomizeQuickAccessToolbar" to "Customize Quick Access Toolbar",
        "MoreCommands" to "More Commands...",
        "AddToQuickAccessToolbar" to "Add to Quick Access Toolbar",
        "RemoveFromQuickAccessToolbar" to "Remove from Quick Access Toolbar",
        "CustomizeRibbon" to "Customize the Ribbon...",
        "MoreOptions" to "More options",
        "SplitButtonOptions" to "{0} options",
        "ZoomIn" to "Zoom in",
        "ZoomOut" to "Zoom out",
        "Zoom" to "Zoom",
        "InvalidImport" to "The text is not a valid ribbon customization (JSON). Nothing was imported.",
        "Search" to "Search",
        "SearchPlaceholder" to "Search (Alt+Q)",
        "SearchNoResults" to "No results",
        "SearchRecent" to "Recently used",
        "SearchActions" to "Actions",
        "Back" to "Back",
        "Automatic" to "Automatic",
        "NoColor" to "No Color",
        "MoreColors" to "More Colors...",
        "ThemeColors" to "Theme Colors",
        "StandardColors" to "Standard Colors",
        "RecentColors" to "Recent Colors",
        "ScrollLeft" to "Scroll left",
        "ScrollRight" to "Scroll right",
        "GalleryUp" to "Row up",
        "GalleryDown" to "Row down",
        "GalleryMore" to "More",
        "GalleryFilter" to "Filter",
        "DialogLauncher" to "{0} Settings",
        "TablePickerFormat" to "{0}x{1} Table",
        "InsertTable" to "Insert Table",
        "Ok" to "OK",
        "Cancel" to "Cancel",
        "Reset" to "Reset",
        "NewTab" to "New Tab",
        "NewGroup" to "New Group",
        "Rename" to "Rename...",
        "Add" to "Add >>",
        "Remove" to "<< Remove",
        "MoveUp" to "Move Up",
        "MoveDown" to "Move Down",
        "ImportExport" to "Import/Export",
        "ChooseCommands" to "Choose commands",
        "MainTabs" to "Main Tabs",
        "QuickAccessToolbar" to "Quick Access Toolbar",
        "CustomGroupSuffix" to "(Custom)",
        "KeyTipsHint" to "Press a key to choose a command. Press Esc to go back.",
        "Close" to "Close",
        "Account" to "Account",
        "Options" to "Options",
        "CommandPalette" to "Type a command",
    )
}
