package com.appkitbox.winui4k.ribbon

/** The French (fr) strings of [RibbonStrings] (exactly as defined by RibbonSpace). */
internal object RibbonStringsFr {
    val VALUES: Map<String, String> = linkedMapOf(
        "File" to "Fichier",
        "CollapseRibbon" to "Réduire le ruban",
        "PinRibbon" to "Épingler le ruban",
        "RibbonDisplayOptions" to "Options d'affichage du ruban",
        "FullScreenMode" to "Mode plein écran",
        "ShowTabsOnly" to "Afficher uniquement les onglets",
        "AlwaysShowRibbon" to "Toujours afficher le ruban",
        "ShowPanelButtons" to "Afficher les boutons des groupes",
        "ShowPanelTitles" to "Afficher les titres des groupes",
        "MinimizeToTabs" to "Réduire aux onglets",
        "MinimizeToPanelTitles" to "Réduire aux titres des groupes",
        "MinimizeToPanelButtons" to "Réduire aux boutons des groupes",
        "CycleThroughAll" to "Parcourir tous les états",
        "MinimizeRibbon" to "Réduire le ruban",
        "ShowFullRibbon" to "Afficher le ruban complet",
        "ShowTabs" to "Afficher les onglets",
        "ShowPanels" to "Afficher les groupes",
        "ShowGroupTitles" to "Afficher les titres des groupes",
        "FloatPanel" to "Détacher le groupe",
        "ReturnPanelToRibbon" to "Remettre le groupe dans le ruban",
        "ReturnPanelsToRibbon" to "Remettre les groupes dans le ruban",
        "PinPanel" to "Garder le groupe ouvert",
        "UnpinPanel" to "Libérer le groupe",
        "ExpandPanel" to "Autres commandes : {0}",
        "RecentDocuments" to "Documents récents",
        "SearchCommands" to "Rechercher des commandes",
        "UseSimplifiedRibbon" to "Ruban simplifié",
        "UseClassicRibbon" to "Ruban classique",
        "ShowQuickAccessToolbar" to "Afficher la barre d'outils Accès rapide",
        "HideQuickAccessToolbar" to "Masquer la barre d'outils Accès rapide",
        "ShowAboveRibbon" to "Afficher au-dessus du ruban",
        "ShowBelowRibbon" to "Afficher sous le ruban",
        "ShowCommandLabels" to "Afficher les étiquettes de commande",
        "CustomizeQuickAccessToolbar" to "Personnaliser la barre d'outils Accès rapide",
        "MoreCommands" to "Autres commandes...",
        "AddToQuickAccessToolbar" to "Ajouter à la barre d'outils Accès rapide",
        "RemoveFromQuickAccessToolbar" to "Supprimer de la barre d'outils Accès rapide",
        "CustomizeRibbon" to "Personnaliser le ruban...",
        "MoreOptions" to "Plus d'options",
        "SplitButtonOptions" to "Options de {0}",
        "ZoomIn" to "Zoom avant",
        "ZoomOut" to "Zoom arrière",
        "Zoom" to "Zoom",
        "InvalidImport" to "Le texte n'est pas une personnalisation du ruban valide (JSON). Rien n'a été importé.",
        "Search" to "Rechercher",
        "SearchPlaceholder" to "Rechercher (Alt+Q)",
        "SearchNoResults" to "Aucun résultat",
        "SearchRecent" to "Récemment utilisées",
        "SearchActions" to "Actions",
        "Back" to "Retour",
        "Automatic" to "Automatique",
        "NoColor" to "Aucune couleur",
        "MoreColors" to "Autres couleurs...",
        "ThemeColors" to "Couleurs du thème",
        "StandardColors" to "Couleurs standard",
        "RecentColors" to "Couleurs récentes",
        "ScrollLeft" to "Défiler vers la gauche",
        "ScrollRight" to "Défiler vers la droite",
        "GalleryUp" to "Ligne précédente",
        "GalleryDown" to "Ligne suivante",
        "GalleryMore" to "Plus",
        "GalleryFilter" to "Filtrer",
        "DialogLauncher" to "Paramètres {0}",
        "TablePickerFormat" to "Tableau {0}x{1}",
        "InsertTable" to "Insérer un tableau",
        "Ok" to "OK",
        "Cancel" to "Annuler",
        "Reset" to "Réinitialiser",
        "NewTab" to "Nouvel onglet",
        "NewGroup" to "Nouveau groupe",
        "Rename" to "Renommer...",
        "Add" to "Ajouter >>",
        "Remove" to "<< Supprimer",
        "MoveUp" to "Monter",
        "MoveDown" to "Descendre",
        "ImportExport" to "Importer/Exporter",
        "ChooseCommands" to "Choisir les commandes",
        "MainTabs" to "Onglets principaux",
        "QuickAccessToolbar" to "Barre d'outils Accès rapide",
        "CustomGroupSuffix" to "(Personnalisé)",
        "KeyTipsHint" to "Appuyez sur une touche pour choisir une commande. Échap pour revenir.",
        "Close" to "Fermer",
        "Account" to "Compte",
        "Options" to "Options",
        "CommandPalette" to "Tapez une commande",
    )
}
