package com.appkitbox.winui4k.ribbon

/** The German (de) strings of [RibbonStrings] (exactly as defined by RibbonSpace). */
internal object RibbonStringsDe {
    val VALUES: Map<String, String> = linkedMapOf(
        "File" to "Datei",
        "CollapseRibbon" to "Menüband reduzieren",
        "PinRibbon" to "Menüband fixieren",
        "RibbonDisplayOptions" to "Menüband-Anzeigeoptionen",
        "FullScreenMode" to "Vollbildmodus",
        "ShowTabsOnly" to "Nur Registerkarten anzeigen",
        "AlwaysShowRibbon" to "Menüband immer anzeigen",
        "ShowPanelButtons" to "Gruppenschaltflächen anzeigen",
        "ShowPanelTitles" to "Gruppentitel anzeigen",
        "MinimizeToTabs" to "Auf Registerkarten minimieren",
        "MinimizeToPanelTitles" to "Auf Gruppentitel minimieren",
        "MinimizeToPanelButtons" to "Auf Gruppenschaltflächen minimieren",
        "CycleThroughAll" to "Alle durchlaufen",
        "MinimizeRibbon" to "Menüband minimieren",
        "ShowFullRibbon" to "Vollständiges Menüband anzeigen",
        "ShowTabs" to "Registerkarten anzeigen",
        "ShowPanels" to "Gruppen anzeigen",
        "ShowGroupTitles" to "Gruppentitel anzeigen",
        "FloatPanel" to "Gruppe lösen",
        "ReturnPanelToRibbon" to "Gruppe an Menüband zurückgeben",
        "ReturnPanelsToRibbon" to "Gruppen an Menüband zurückgeben",
        "PinPanel" to "Gruppe geöffnet lassen",
        "UnpinPanel" to "Gruppe lösen",
        "ExpandPanel" to "Weitere Befehle: {0}",
        "RecentDocuments" to "Zuletzt verwendete Dokumente",
        "SearchCommands" to "Befehle suchen",
        "UseSimplifiedRibbon" to "Vereinfachtes Menüband",
        "UseClassicRibbon" to "Klassisches Menüband",
        "ShowQuickAccessToolbar" to "Symbolleiste für den Schnellzugriff anzeigen",
        "HideQuickAccessToolbar" to "Symbolleiste für den Schnellzugriff ausblenden",
        "ShowAboveRibbon" to "Über dem Menüband anzeigen",
        "ShowBelowRibbon" to "Unter dem Menüband anzeigen",
        "ShowCommandLabels" to "Befehlsbeschriftungen anzeigen",
        "CustomizeQuickAccessToolbar" to "Symbolleiste für den Schnellzugriff anpassen",
        "MoreCommands" to "Weitere Befehle...",
        "AddToQuickAccessToolbar" to "Zu Symbolleiste für den Schnellzugriff hinzufügen",
        "RemoveFromQuickAccessToolbar" to "Aus Symbolleiste für den Schnellzugriff entfernen",
        "CustomizeRibbon" to "Menüband anpassen...",
        "MoreOptions" to "Weitere Optionen",
        "SplitButtonOptions" to "{0} – Optionen",
        "ZoomIn" to "Vergrößern",
        "ZoomOut" to "Verkleinern",
        "Zoom" to "Zoom",
        "InvalidImport" to "Der Text ist keine gültige Menüband-Anpassung (JSON). Es wurde nichts importiert.",
        "Search" to "Suchen",
        "SearchPlaceholder" to "Suchen (Alt+Q)",
        "SearchNoResults" to "Keine Ergebnisse",
        "SearchRecent" to "Zuletzt verwendet",
        "SearchActions" to "Aktionen",
        "Back" to "Zurück",
        "Automatic" to "Automatisch",
        "NoColor" to "Keine Farbe",
        "MoreColors" to "Weitere Farben...",
        "ThemeColors" to "Designfarben",
        "StandardColors" to "Standardfarben",
        "RecentColors" to "Zuletzt verwendete Farben",
        "ScrollLeft" to "Nach links scrollen",
        "ScrollRight" to "Nach rechts scrollen",
        "GalleryUp" to "Zeile nach oben",
        "GalleryDown" to "Zeile nach unten",
        "GalleryMore" to "Mehr",
        "GalleryFilter" to "Filtern",
        "DialogLauncher" to "{0}-Einstellungen",
        "TablePickerFormat" to "{0}x{1}-Tabelle",
        "InsertTable" to "Tabelle einfügen",
        "Ok" to "OK",
        "Cancel" to "Abbrechen",
        "Reset" to "Zurücksetzen",
        "NewTab" to "Neue Registerkarte",
        "NewGroup" to "Neue Gruppe",
        "Rename" to "Umbenennen...",
        "Add" to "Hinzufügen >>",
        "Remove" to "<< Entfernen",
        "MoveUp" to "Nach oben",
        "MoveDown" to "Nach unten",
        "ImportExport" to "Importieren/Exportieren",
        "ChooseCommands" to "Befehle auswählen",
        "MainTabs" to "Hauptregisterkarten",
        "QuickAccessToolbar" to "Symbolleiste für den Schnellzugriff",
        "CustomGroupSuffix" to "(Benutzerdefiniert)",
        "KeyTipsHint" to "Drücken Sie eine Taste, um einen Befehl auszuwählen. Esc für zurück.",
        "Close" to "Schließen",
        "Account" to "Konto",
        "Options" to "Optionen",
        "CommandPalette" to "Befehl eingeben",
    )
}
