package com.appkitbox.winui4k.table

import com.appkitbox.winui4k.SpinButtonPlacementMode
import com.appkitbox.winui4k.TableViewXaml
import com.appkitbox.winui4k.UiTestHarness.onUiThreadGet
import com.appkitbox.winui4k.WCheckBox
import com.appkitbox.winui4k.WComboBox
import com.appkitbox.winui4k.WSlider
import com.appkitbox.winui4k.WSpinner
import com.appkitbox.winui4k.WTextField
import com.appkitbox.winui4k.WToggleSwitch
import com.appkitbox.winui4k.internal.ffi.api.Ffi
import com.appkitbox.winui4k.internal.ffi.api.withScope
import com.appkitbox.winui4k.internal.winrt.Hstring
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain

/**
 * Tests that the editor XAML generated by DefaultCellEditor can be loaded as a DataTemplate
 * (XamlReader.Load + LoadContent) and produces the expected control.
 */
class DefaultCellEditorTest : FunSpec() {
    /** Creates one editor from the template of [editor] and returns its runtime class name. */
    private fun loadEditorClassName(editor: TableCellEditor): String {
        val template = TableViewXaml.createDataTemplate(editor.getCellEditorXaml("c0"))
        val content = template.getPtr(6) // IDataTemplate.LoadContent
        template.release()
        return try {
            Ffi.backend.withScope { scope ->
                val out = scope.allocate(8)
                content.call(4, out) // IInspectable::GetRuntimeClassName
                val hstring = Ffi.backend.memory.getPtr(out, 0)
                Hstring.read(hstring).also { Hstring.free(hstring) }
            }
        } finally {
            content.release()
        }
    }

    init {
        test("an editor created from each component can be loaded as a DataTemplate of that control") {
            onUiThreadGet {
                listOf(
                    DefaultCellEditor(WTextField("Input")),
                    DefaultCellEditor(WCheckBox("Enabled")),
                    DefaultCellEditor(WComboBox(listOf("Development", "Sales & Admin"))),
                    DefaultCellEditor(WToggleSwitch().also { it.onContent = "On" }),
                    DefaultCellEditor(WSlider(0.0, 10.0)),
                    DefaultCellEditor(WSpinner().also { it.spinButtonPlacementMode = SpinButtonPlacementMode.INLINE }),
                ).map { loadEditorClassName(it) }
            } shouldBe listOf(
                "Microsoft.UI.Xaml.Controls.TextBox",
                "Microsoft.UI.Xaml.Controls.CheckBox",
                "Microsoft.UI.Xaml.Controls.ComboBox",
                "Microsoft.UI.Xaml.Controls.ToggleSwitch",
                "Microsoft.UI.Xaml.Controls.Slider",
                "Microsoft.UI.Xaml.Controls.NumberBox",
            )
        }

        test("the editor value is bound TwoWay with Explicit updates (so Esc can cancel), and XAML special characters are escaped") {
            val xaml = onUiThreadGet { DefaultCellEditor(WComboBox(listOf("<A&B>"))).getCellEditorXaml("c3") }
            xaml shouldContain "SelectedItem=\"{Binding c3, Mode=TwoWay, UpdateSourceTrigger=Explicit}\""
            xaml shouldContain "<x:String>&lt;A&amp;B&gt;</x:String>"
        }
    }
}
