package com.appkitbox.winui4k.extension.ribbon.model

/** The Polish (pl) strings of [RibbonStrings] (exactly as defined by RibbonSpace). */
internal object RibbonStringsPl {
    val VALUES: Map<String, String> = linkedMapOf(
        "File" to "Plik",
        "CollapseRibbon" to "Zwiń wstążkę",
        "PinRibbon" to "Przypnij wstążkę",
        "RibbonDisplayOptions" to "Opcje wyświetlania wstążki",
        "FullScreenMode" to "Tryb pełnoekranowy",
        "ShowTabsOnly" to "Pokaż tylko karty",
        "AlwaysShowRibbon" to "Zawsze pokazuj wstążkę",
        "ShowPanelButtons" to "Pokaż przyciski grup",
        "ShowPanelTitles" to "Pokaż tytuły grup",
        "MinimizeToTabs" to "Minimalizuj do kart",
        "MinimizeToPanelTitles" to "Minimalizuj do tytułów grup",
        "MinimizeToPanelButtons" to "Minimalizuj do przycisków grup",
        "CycleThroughAll" to "Przełączaj wszystkie",
        "MinimizeRibbon" to "Minimalizuj wstążkę",
        "ShowFullRibbon" to "Pokaż pełną wstążkę",
        "ShowTabs" to "Pokaż karty",
        "ShowPanels" to "Pokaż grupy",
        "ShowGroupTitles" to "Pokaż tytuły grup",
        "FloatPanel" to "Odepnij grupę",
        "ReturnPanelToRibbon" to "Przywróć grupę do wstążki",
        "ReturnPanelsToRibbon" to "Przywróć grupy do wstążki",
        "PinPanel" to "Zostaw grupę otwartą",
        "UnpinPanel" to "Odepnij grupę",
        "ExpandPanel" to "Więcej poleceń: {0}",
        "RecentDocuments" to "Ostatnie dokumenty",
        "SearchCommands" to "Szukaj poleceń",
        "UseSimplifiedRibbon" to "Uproszczona wstążka",
        "UseClassicRibbon" to "Klasyczna wstążka",
        "ShowQuickAccessToolbar" to "Pokaż pasek narzędzi Szybki dostęp",
        "HideQuickAccessToolbar" to "Ukryj pasek narzędzi Szybki dostęp",
        "ShowAboveRibbon" to "Pokaż nad wstążką",
        "ShowBelowRibbon" to "Pokaż pod wstążką",
        "ShowCommandLabels" to "Pokaż etykiety poleceń",
        "CustomizeQuickAccessToolbar" to "Dostosuj pasek narzędzi Szybki dostęp",
        "MoreCommands" to "Więcej poleceń...",
        "AddToQuickAccessToolbar" to "Dodaj do paska narzędzi Szybki dostęp",
        "RemoveFromQuickAccessToolbar" to "Usuń z paska narzędzi Szybki dostęp",
        "CustomizeRibbon" to "Dostosuj wstążkę...",
        "MoreOptions" to "Więcej opcji",
        "SplitButtonOptions" to "{0} – opcje",
        "ZoomIn" to "Powiększ",
        "ZoomOut" to "Pomniejsz",
        "Zoom" to "Powiększenie",
        "InvalidImport" to "Tekst nie jest prawidłowym dostosowaniem wstążki (JSON). Nic nie zaimportowano.",
        "Search" to "Wyszukaj",
        "SearchPlaceholder" to "Wyszukaj (Alt+Q)",
        "SearchNoResults" to "Brak wyników",
        "SearchRecent" to "Ostatnio używane",
        "SearchActions" to "Akcje",
        "Back" to "Wstecz",
        "Automatic" to "Automatyczny",
        "NoColor" to "Brak koloru",
        "MoreColors" to "Więcej kolorów...",
        "ThemeColors" to "Kolory motywu",
        "StandardColors" to "Kolory standardowe",
        "RecentColors" to "Ostatnie kolory",
        "ScrollLeft" to "Przewiń w lewo",
        "ScrollRight" to "Przewiń w prawo",
        "GalleryUp" to "Wiersz w górę",
        "GalleryDown" to "Wiersz w dół",
        "GalleryMore" to "Więcej",
        "GalleryFilter" to "Filtruj",
        "DialogLauncher" to "Ustawienia: {0}",
        "TablePickerFormat" to "Tabela {0}x{1}",
        "InsertTable" to "Wstaw tabelę",
        "Ok" to "OK",
        "Cancel" to "Anuluj",
        "Reset" to "Resetuj",
        "NewTab" to "Nowa karta",
        "NewGroup" to "Nowa grupa",
        "Rename" to "Zmień nazwę...",
        "Add" to "Dodaj >>",
        "Remove" to "<< Usuń",
        "MoveUp" to "Przenieś w górę",
        "MoveDown" to "Przenieś w dół",
        "ImportExport" to "Importuj/Eksportuj",
        "ChooseCommands" to "Wybierz polecenia",
        "MainTabs" to "Karty główne",
        "QuickAccessToolbar" to "Pasek narzędzi Szybki dostęp",
        "CustomGroupSuffix" to "(Niestandardowa)",
        "KeyTipsHint" to "Naciśnij klawisz, aby wybrać polecenie. Esc – wstecz.",
        "Close" to "Zamknij",
        "Account" to "Konto",
        "Options" to "Opcje",
        "CommandPalette" to "Wpisz polecenie",
    )
}
