package com.appkitbox.winui4k.extension.ribbon.model

/**
 * The Japanese (ja) strings of [RibbonStrings]. These translations were added by winui4k, and the terminology follows
 * the Japanese version of Microsoft Office (and the Japanese version of AutoCAD for features that come from AutoCAD).
 */
internal object RibbonStringsJa {
    val VALUES: Map<String, String> = linkedMapOf(
        "File" to "ファイル",
        "CollapseRibbon" to "リボンを折りたたむ",
        "PinRibbon" to "リボンの固定",
        "RibbonDisplayOptions" to "リボンの表示オプション",
        "FullScreenMode" to "全画面表示モード",
        "ShowTabsOnly" to "タブのみを表示する",
        "AlwaysShowRibbon" to "常にリボンを表示する",
        "ShowPanelButtons" to "パネル ボタンを表示する",
        "ShowPanelTitles" to "パネル タイトルを表示する",
        "MinimizeToTabs" to "タブに最小化",
        "MinimizeToPanelTitles" to "パネル タイトルに最小化",
        "MinimizeToPanelButtons" to "パネル ボタンに最小化",
        "CycleThroughAll" to "すべてを順に切り替え",
        "MinimizeRibbon" to "リボンを最小化",
        "ShowFullRibbon" to "リボン全体を表示",
        "ShowTabs" to "タブを表示",
        "ShowPanels" to "パネルを表示",
        "ShowGroupTitles" to "パネル タイトルを表示",
        "FloatPanel" to "パネルをフローティング",
        "ReturnPanelToRibbon" to "パネルをリボンに戻す",
        "ReturnPanelsToRibbon" to "すべてのパネルをリボンに戻す",
        "PinPanel" to "パネルを開いたままにする",
        "UnpinPanel" to "パネルの固定を解除",
        "ExpandPanel" to "{0} のその他のコマンド",
        "RecentDocuments" to "最近使用したドキュメント",
        "SearchCommands" to "コマンドを検索",
        "UseSimplifiedRibbon" to "シンプル リボン",
        "UseClassicRibbon" to "クラシック リボン",
        "ShowQuickAccessToolbar" to "クイック アクセス ツール バーを表示する",
        "HideQuickAccessToolbar" to "クイック アクセス ツール バーを非表示にする",
        "ShowAboveRibbon" to "リボンの上に表示",
        "ShowBelowRibbon" to "リボンの下に表示",
        "ShowCommandLabels" to "コマンド ラベルを表示",
        "CustomizeQuickAccessToolbar" to "クイック アクセス ツール バーのユーザー設定",
        "MoreCommands" to "その他のコマンド...",
        "AddToQuickAccessToolbar" to "クイック アクセス ツール バーに追加",
        "RemoveFromQuickAccessToolbar" to "クイック アクセス ツール バーから削除",
        "CustomizeRibbon" to "リボンのユーザー設定...",
        "MoreOptions" to "その他のオプション",
        "SplitButtonOptions" to "{0} のオプション",
        "ZoomIn" to "拡大",
        "ZoomOut" to "縮小",
        "Zoom" to "ズーム",
        "InvalidImport" to "テキストが有効なリボンのユーザー設定 (JSON) ではありません。何もインポートされませんでした。",
        "Search" to "検索",
        "SearchPlaceholder" to "検索 (Alt+Q)",
        "SearchNoResults" to "結果がありません",
        "SearchRecent" to "最近使用したもの",
        "SearchActions" to "操作",
        "Back" to "戻る",
        "Automatic" to "自動",
        "NoColor" to "色なし",
        "MoreColors" to "その他の色...",
        "ThemeColors" to "テーマの色",
        "StandardColors" to "標準の色",
        "RecentColors" to "最近使用した色",
        "ScrollLeft" to "左へスクロール",
        "ScrollRight" to "右へスクロール",
        "GalleryUp" to "前の行",
        "GalleryDown" to "次の行",
        "GalleryMore" to "その他",
        "GalleryFilter" to "フィルター",
        "DialogLauncher" to "{0} の設定",
        "TablePickerFormat" to "{0}x{1} 表",
        "InsertTable" to "表の挿入",
        "Ok" to "OK",
        "Cancel" to "キャンセル",
        "Reset" to "リセット",
        "NewTab" to "新しいタブ",
        "NewGroup" to "新しいグループ",
        "Rename" to "名前の変更...",
        "Add" to "追加 >>",
        "Remove" to "<< 削除",
        "MoveUp" to "上へ移動",
        "MoveDown" to "下へ移動",
        "ImportExport" to "インポート/エクスポート",
        "ChooseCommands" to "コマンドの選択",
        "MainTabs" to "メイン タブ",
        "QuickAccessToolbar" to "クイック アクセス ツール バー",
        "CustomGroupSuffix" to "(ユーザー設定)",
        "KeyTipsHint" to "キーを押してコマンドを選択します。Esc キーで前に戻ります。",
        "Close" to "閉じる",
        "Account" to "アカウント",
        "Options" to "オプション",
        "CommandPalette" to "コマンドを入力",
    )
}
