package com.appkitbox.winui4k.extension.ribbon.model

/** The Spanish (es) strings of [RibbonStrings] (exactly as defined by RibbonSpace). */
internal object RibbonStringsEs {
    val VALUES: Map<String, String> = linkedMapOf(
        "File" to "Archivo",
        "CollapseRibbon" to "Contraer la cinta de opciones",
        "PinRibbon" to "Anclar la cinta de opciones",
        "RibbonDisplayOptions" to "Opciones de presentación de la cinta",
        "FullScreenMode" to "Modo de pantalla completa",
        "ShowTabsOnly" to "Mostrar solo pestañas",
        "AlwaysShowRibbon" to "Mostrar siempre la cinta",
        "ShowPanelButtons" to "Mostrar botones de grupos",
        "ShowPanelTitles" to "Mostrar títulos de grupos",
        "MinimizeToTabs" to "Minimizar a pestañas",
        "MinimizeToPanelTitles" to "Minimizar a títulos de grupos",
        "MinimizeToPanelButtons" to "Minimizar a botones de grupos",
        "CycleThroughAll" to "Recorrer todos",
        "MinimizeRibbon" to "Minimizar la cinta",
        "ShowFullRibbon" to "Mostrar la cinta completa",
        "ShowTabs" to "Mostrar pestañas",
        "ShowPanels" to "Mostrar grupos",
        "ShowGroupTitles" to "Mostrar títulos de grupos",
        "FloatPanel" to "Desacoplar grupo",
        "ReturnPanelToRibbon" to "Devolver grupo a la cinta",
        "ReturnPanelsToRibbon" to "Devolver grupos a la cinta",
        "PinPanel" to "Mantener grupo abierto",
        "UnpinPanel" to "Desanclar grupo",
        "ExpandPanel" to "Más comandos de {0}",
        "RecentDocuments" to "Documentos recientes",
        "SearchCommands" to "Buscar comandos",
        "UseSimplifiedRibbon" to "Cinta de opciones simplificada",
        "UseClassicRibbon" to "Cinta de opciones clásica",
        "ShowQuickAccessToolbar" to "Mostrar barra de herramientas de acceso rápido",
        "HideQuickAccessToolbar" to "Ocultar barra de herramientas de acceso rápido",
        "ShowAboveRibbon" to "Mostrar encima de la cinta",
        "ShowBelowRibbon" to "Mostrar debajo de la cinta",
        "ShowCommandLabels" to "Mostrar etiquetas de comandos",
        "CustomizeQuickAccessToolbar" to "Personalizar barra de herramientas de acceso rápido",
        "MoreCommands" to "Más comandos...",
        "AddToQuickAccessToolbar" to "Agregar a la barra de herramientas de acceso rápido",
        "RemoveFromQuickAccessToolbar" to "Quitar de la barra de herramientas de acceso rápido",
        "CustomizeRibbon" to "Personalizar la cinta de opciones...",
        "MoreOptions" to "Más opciones",
        "SplitButtonOptions" to "Opciones de {0}",
        "ZoomIn" to "Acercar",
        "ZoomOut" to "Alejar",
        "Zoom" to "Zoom",
        "InvalidImport" to "El texto no es una personalización de la cinta válida (JSON). No se importó nada.",
        "Search" to "Buscar",
        "SearchPlaceholder" to "Buscar (Alt+Q)",
        "SearchNoResults" to "No hay resultados",
        "SearchRecent" to "Usados recientemente",
        "SearchActions" to "Acciones",
        "Back" to "Atrás",
        "Automatic" to "Automático",
        "NoColor" to "Sin color",
        "MoreColors" to "Más colores...",
        "ThemeColors" to "Colores del tema",
        "StandardColors" to "Colores estándar",
        "RecentColors" to "Colores recientes",
        "ScrollLeft" to "Desplazar a la izquierda",
        "ScrollRight" to "Desplazar a la derecha",
        "GalleryUp" to "Fila anterior",
        "GalleryDown" to "Fila siguiente",
        "GalleryMore" to "Más",
        "GalleryFilter" to "Filtrar",
        "DialogLauncher" to "Configuración de {0}",
        "TablePickerFormat" to "Tabla de {0}x{1}",
        "InsertTable" to "Insertar tabla",
        "Ok" to "Aceptar",
        "Cancel" to "Cancelar",
        "Reset" to "Restablecer",
        "NewTab" to "Nueva pestaña",
        "NewGroup" to "Nuevo grupo",
        "Rename" to "Cambiar nombre...",
        "Add" to "Agregar >>",
        "Remove" to "<< Quitar",
        "MoveUp" to "Subir",
        "MoveDown" to "Bajar",
        "ImportExport" to "Importar/Exportar",
        "ChooseCommands" to "Comandos disponibles",
        "MainTabs" to "Pestañas principales",
        "QuickAccessToolbar" to "Barra de herramientas de acceso rápido",
        "CustomGroupSuffix" to "(Personalizado)",
        "KeyTipsHint" to "Presione una tecla para elegir un comando. Esc para volver.",
        "Close" to "Cerrar",
        "Account" to "Cuenta",
        "Options" to "Opciones",
        "CommandPalette" to "Escriba un comando",
    )
}
